### ISSUE TITLE
Archive-IT Seed Import Failure

### ISSUE THREAD

**Issue by seth-shaw-unlv** [bentley-historical-library/bhl_aspace_archive_it#3]
We attempted to install the plugin according to the instructions; but when we attempted to import a seed we received a 500 error:
```
I, [2020-03-02T10:38:59.050923 #27911]  INFO -- : Processing by ArchiveItController#import as HTML
I, [2020-03-02T10:38:59.051085 #27911]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[REDACTED]", "seed_url"=>"https://partner.archive-it.org/755/collections/13488/seeds/2145033"}
I, [2020-03-02T10:39:59.097808 #27911]  INFO -- : Completed 500 Internal Server Error in 60046ms
F, [2020-03-02T10:39:59.102558 #27911] FATAL -- :   
F, [2020-03-02T10:39:59.102727 #27911] FATAL -- : Net::OpenTimeout (Failed to open TCP connection to partner.archive-it.org:443 (execution expired)):
F, [2020-03-02T10:39:59.102874 #27911] FATAL -- :   
F, [2020-03-02T10:39:59.103381 #27911] FATAL -- : org/jruby/ext/socket/RubyTCPSocket.java:112:in `initialize'
org/jruby/RubyIO.java:1137:in `open'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:885:in `block in connect'
org/jruby/ext/timeout/Timeout.java:149:in `timeout'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:883:in `connect'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:868:in `do_start'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:857:in `start'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:585:in `start'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:480:in `get_response'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:457:in `get'
/data/archivesspace/plugins/bhl_aspace_archive_it/frontend/models/archive_it.rb:17:in `get_seed_metadata'
/data/archivesspace/plugins/bhl_aspace_archive_it/frontend/models/archive_it.rb:35:in `create_archival_object'
/data/archivesspace/plugins/bhl_aspace_archive_it/frontend/controllers/archive_it_controller.rb:21:in `import'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block in compile'
activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:36:in `block in process_action'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
org/jruby/RubyArray.java:1734:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
uri:classloader:/rack/handler/servlet.rb:22:in `call'
```

Visiting the seed manually via a browser redirects us to a login page, which makes sense. This prompted me to realize that the instructions don't indicate where one should include Archive-IT login information. Is this part of the archivesspace `config.rb` file? I don't see any configuration page in the Web UI...

**Comment by seth-shaw-unlv** [comment]
Two things:

First, our test box is on a private network that was preventing external requests. I didn't realize this was an issue because the lcnaf plugin works. Turns out that we had modified it to work with a proxy and I hadn't realized that. 🤦‍♂️ Fortunately, that is quickly fixed by replacing [this line](https://github.com/bentley-historical-library/bhl_aspace_archive_it/blob/master/frontend/models/archive_it.rb#L17) with 
```ruby
        proxy_uri  = URI.parse(ENV['http_proxy'])
        proxy_class = Net::HTTP::Proxy(proxy_uri.host, proxy_uri.port)
        response = proxy_class.get(api_uri)
```
although I'm sure we could throw in some logic to detect the proxy settings and use the appropriate class accordingly.

Second, importing a seed with a collection not in the config.rb mapping throws a WSOD. That should probably fail more gracefully.

Thanks for your help, @djpillen, in helping me figure this out on Slack!
